version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: gclass-rabbitmq
    ports:
      - "5672:5672"   # Cổng để App kết nối (đã config trong yaml)
      - "15672:15672"
      - "61613:61613"
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest